title: My title
author: curent user
email: dhenebygold@domain.com
description: > # this means to ignore newlines until "baseurl:"
  to customise yuor site

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
